apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudforge-ai.fullname" . }}-frontend
  labels:
    app: {{ include "cloudforge-ai.name" . }}
    component: frontend
spec:
  replicas: {{ .Values.replicaCount.frontend }}
  selector:
    matchLabels:
      app: {{ include "cloudforge-ai.name" . }}
      component: frontend
  template:
    metadata:
      labels:
        app: {{ include "cloudforge-ai.name" . }}
        component: frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.image.repository.frontend }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources.frontend | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloudforge-ai.fullname" . }}-frontend
  labels:
    app: {{ include "cloudforge-ai.name" . }}
    component: frontend
spec:
  type: {{ .Values.service.frontend.type }}
  selector:
    app: {{ include "cloudforge-ai.name" . }}
    component: frontend
  ports:
    - name: http
      port: {{ .Values.service.frontend.port }}
      targetPort: 3000
