apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-hpa
  namespace: cloudforge
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: cloudforge-ai
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
