apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.39
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: cloudforge2025
            - name: MYSQL_DATABASE
              value: chinook
            - name: MYSQL_USER
              value: cloudforge
            - name: MYSQL_PASSWORD
              value: cloudforge2025
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
