name: Deploy to Minikube (CI)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Frontend Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/frontend:latest ./frontend

      - name: Build Backend Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/backend:latest ./backend

      - name: Upload k8s manifests as artifact
        uses: actions/upload-artifact@v4
        with:
          name: k8s-manifests
          path: infra/k8s-manifests/

# TEST: CI deploy workflow scaffolding
